Lambda-School-Labs/CS9-KnowledgeRocket

.gitignore
=> ignore env files

pull_request_template.md
=> returns PR template to repo

.travis.yml
=> travis file to run tests

.travis.yml
=> attempt to deploy to heroku

server/server.js
=> bugfix:  removes facebook router since it doesn't exist.

.travis.yml
=> deploy should have skip_cleanup higher up

client/package-lock.json, client/src/components/Home/Home.js, client/src/index.js, server/package-lock.json
=> removes unused vars and updates deps

server/tests/server.spec.js, server/yarn.lock
Created test for every model/schema. All tests pass. Doesn't touch the production db.
Also changes the server.js so it runs from index for testing safety purposes. 
=> Brandon: Basic Backend Testing Suite Done

.prettierrc.json
=> Added prettier config

README.md, client/README.md, pull_request_template.md
The template was just that, a template. This PR updates the template with things relevant to our project. On that note it also creates a TOC in our main readme for our project.
=> chore: Readme and template update

server/auth/AuthRouter.js, server/responserocket/ResponseRocket.js, server/server.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Moises: Changes to new users from email.

client/src/actions/index.js, client/src/components/Billing/Billing.css, client/src/components/Billing/Billing.js, client/src/components/Billing/checkout.js, client/src/reducers/userReducers.js, server/auth/AuthRouter.js, server/server.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: Reverted back to embedded for the client's preference

server/billing/BillingRouter.js, server/server.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: Moved Billing from Server.js to BillingRouter.js

client/src/components/Cohort/Cohort.js, client/src/components/CohortAddStudentsForm/CohortAddStudentsForm.js, client/src/components/CohortCard/CohortCard.js, client/src/components/CohortList/CohortList.js, client/src/components/CohortRocketCard/CohortRocketCard.js, client/src/components/CohortRocketList/CohortRocketList.js, client/src/components/CohortSettingForm/CohortSettingForm.js, client/src/components/CohortStudentCard/CohortStudentCard.js, client/src/components/CohortStudentList/CohortStudentList.js, client/src/components/Routes/index.js, client/src/tests/CohortCard.test.js, client/src/tests/CohortList.test.js, client/src/tests/__snapshots__/CohortCard.test.js.snap, client/src/tests/__snapshots__/CohortList.test.js.snap
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
1. Created Links around add new class/add new buttons to link to Cohort component 
2. Created styled container for CohortList
3. Set up basic Cohort view with - cohort settings, add new students, student list, and knowledge rockets sections.
4. Added styles to the Cohort view and its child components
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
=> CohortList and Cohort Views

client/package-lock.json, client/package.json, client/src/components/Auth/Auth.css, client/src/components/Auth/Auth.js, client/src/components/Billing/Billing.css, client/src/components/Billing/Billing.js, client/src/components/Billing/checkout.js, server/question/QuestionRouter.js, server/responserocket/ResponseRocketRouter.js, server/rocket/RocketRouter.js, server/student/StudentRouter.js, server/user/UserRouter.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: Billing Styled looks much better

server/cohort/CohortRouter.js, server/tests/server.spec.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: fixed post test for cohort router

client/package-lock.json, client/src/components/Cohort/Cohort.js, client/src/components/CohortAddStudentsForm/CohortAddStudentsForm.js, client/src/components/CohortStudentCard/CohortStudentCard.js, client/src/reducers/userReducers.js, server/auth/AuthRouter.js, server/student/Student.js, server/student/StudentRouter.js, server/tests/server.spec.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: fixed server tests, student models, student router, and auth router

client/src/actions/index.js, client/src/components/Cohort/Cohort.js, client/src/components/CohortStudentCard/CohortStudentCard.js, client/src/components/ControlPanel/ControlPanel.js, client/src/components/NavBar/NavBar.js, server/student/Student.js, server/student/StudentRouter.js, server/tests/server.spec.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
1. Clicking remove student removes the student document from /api/student
2. Clicking remove student removes the student reference from the students field in Cohort via a pre remove hook
3. Restyled Navbar and ControlPanel using Material Components 
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Implemented Student DELETE, Materialized Navbar and Control Panel

client/src/components/RocketQuestion/RocketQuestion.js, client/src/components/Routes/index.js, server/cohort/CohortRouter.js, server/responserocket/ResponseRocket.js, server/responserocket/ResponseRocketRouter.js, server/rocket/Rocket.js, server/user/User.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Schema updated for: ResponseRocket & User Bug Uncommented

client/package-lock.json, client/src/actions/index.js, client/src/components/Settings/Settings.css, client/src/components/Settings/Settings.js, client/src/reducers/userReducers.js, client/src/tests/__snapshots__/CohortCard.test.js.snap, client/src/tests/__snapshots__/CohortList.test.js.snap, server/auth/AuthRouter.js, server/question/Question.js, server/rocket/Rocket.js, server/rocket/RocketRouter.js, server/tests/server.spec.js, server/user/User.js, server/user/UserRouter.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Request to merge: Settings WIP but Front end Finished.

client/README.md, client/src/components/RocketQuestion/RocketQuestion.css, client/src/components/RocketQuestion/RocketQuestion.js, server/README.md
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: front end for student questions done

client/src/components/RocketQuestion/RocketQuestion.js, server/responserocket/ResponseRocketRouter.js
… for Question Submission
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
-   [x] …
=> Worked in collaboration with Brandon to Create Front End and Back end

README.md
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
In my preliminary research, I found that stickers make a project approximately 463% more _better_. Thus I am including a sticker to the main readme showing the current status of our build. We already run and use travis so this is no extra burden. 
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
-   [ ] Travis …
=> critical: includes sticker

package.json
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> correct endpoint is /api/mail

client/src/actions/index.js, client/src/components/Auth/Auth.js, client/src/components/Auth/AuthBackside.js, client/src/components/Auth/AuthResetPassword.js, client/src/components/CohortList/CohortList.js, client/src/components/CohortSettingForm/CohortSettingForm.js, client/src/components/Home/Home.js, client/src/components/Home/HomeStyled.js, client/src/components/NavBar/NavBar.js, client/src/components/RocketList/ListElements.js, client/src/components/RocketList/RocketList.js, client/src/components/Routes/index.js, client/src/components/Themes/Themes.js, client/src/reducers/userReducers.js, server/cohort/CohortRouter.js, server/student/StudentRouter.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Implemented Password Reset to the Authentication Justin Built. Using the same design flow, on the back card of the Auth Page:
(1) Once the user fails to log-in 3 times, the back card displays the Password Reset Component.
(2) If the user provides a valid e-mail: Firebase will attempt to send them a password reset link.
(3) Then the user is redirected to the main Auth Page:
(3.1) But now the header reads: Please check your email for a password reset link.
(4) The user can keep trying to log-in, but the back card will now always contain the option to Reset Password.
(5) Upon successful log-in all remains as usual.
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
-   [x] New feature …
=> Authentication: Password Reset on 3 Tries / Back-Card Info Improved.

client/src/index.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Fixes Issue with only using logger during developement
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] My code has been …
=> bugfix: apply middleware doesn't accept null. handle with rest operator.

server/mail/MailRouter.js, server/rocket/Rocket.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Have mail take into account cohort id

client/README.md, server/README.md
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: Fixed Readme Spacing 

server/README.md
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: Readme improvement

client/src/actions/index.js, client/src/components/Cohort/Cohort.js, client/src/components/CohortRocketCard/CohortRocketCard.js, client/src/components/CohortRocketList/CohortRocketList.js, client/src/components/RocketList/ListElements.js, client/src/components/RocketQuestion/RocketQuestion.js, client/src/components/RocketResults/RocketResults.js, client/src/components/Routes/index.js, client/src/reducers/index.js, client/src/reducers/rocketReducers.js, server/responserocket/ResponseRocketRouter.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
(1) Corrected a bug where Questions were not properly submitting the answers to the DB.
(2) Completed full implementation and functionality for Results Page:
-       When clicking on a scheduled Rocket's [Results] Button you are navigated to a page that will
display the participation for the current answers and most common answers picked.
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Please describe the tests that you ran to verify your changes. Provide instructions …
=> Questions and Results Report Page

client/src/components/RocketResults/RocketResults.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> remove typo

client/src/components/CohortSettingForm/CohortSettingForm.js, client/src/components/CohortStudentList/CohortStudentList.js, server/student/StudentRouter.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Fixed issue where users could not import CSVs sequentially inside the Cohort view.
Implemented an expansion panel to hold list of student cards
https://github.com/Lambda-School-Labs/CS9-KnowledgeRocket/issues/102
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
-   [x] New feature
-   [x] Manual tests. Please …
=> Fixed issue #102: Sequential CSV importing not functional / Expansion Panel for student cards

client/src/components/RocketList/ListElements.js, client/src/components/RocketList/RocketList.js, client/src/reducers/userReducers.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: Fixed Rocket Delete Bug ._id is not my friend

client/src/components/Cohort/Cohort.js, client/src/components/CohortList/CohortList.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
1. fixed warning: functions are not valid as a React child (Cohort.js)
2. fixed warning: can not call setState on unmounted components (CohortList.js)
https://stackoverflow.com/questions/50428842/cant-call-setstate-or-forceupdate-on-an-unmounted-component
https://stackoverflow.com/questions/50029468/react-warning-about-setstate-in-unmounted-component
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please …
=> Fixed warnings in Cohort views

server/mail/MailRouter.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Fixes email to have correct cohort id and baseurl
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] My code has been reviewed by …
=> get cohort id differently

client/src/actions/index.js, client/src/components/RocketList/RocketList.js, client/src/components/RocketQuestion/RocketQuestion.js, client/src/components/RocketResults/RocketResults.js, client/src/reducers/userReducers.js, server/rocket/RocketRouter.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Questions in Server Updated with Rocket & Rocket Results Accuracy Improved
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own …
=> Questions in Server Updated with Rocket & Rocket Results Accuracy Improved

client/src/components/Home/Home.js, client/src/components/Home/HomeStyled.js, client/src/components/NavBar/NavBar.js, client/src/tests/Home.test.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
Takes into the issues caleb mentioned for the home page
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [ ] My code has been …
=> Homepage updates

client/src/components/Auth/Auth.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: removed color white from styled input

client/src/components/Auth/Auth.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> Brandon: fixed placeholder issue on sign up

client/src/components/Settings/Settings.js
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
❗❗❗❗❗❗❗❗❗❗❗❗❗❗
- …
=> remove semicolon from settings page #120
